### ISSUE TITLE
There is a problem that you cannot connect to a specific bbs.

### ISSUE THREAD

**Issue by kurugai** [nullvalue0/WiRSa#1]
Hi! I'm a user who is using your product very well. Thank you always for your hard work. 

I'm contacting you because there seems to be a bug. If you try to Telnet to a specific bbs, the oled screen turns off and you cannot access it. 

The address is ...

bbs.olddos.kr:9000

This is the bbs I use often, so I'm sorry, but could you fix the bug? Please. 🙏

**Comment by nullvalue0** [comment]
Sorry I am not sure what's going on with this system - I wonder if it is running ANSI detection or some telnet code that the WiRSa isn't responding to - and it's waiting for a response of some kind. Any way you can find out from who's running it why it might hang upon the initial connection?
