### ISSUE TITLE
Add some margin to the 3D Printed Case

### ISSUE THREAD

**Issue by dvincent747** [nullvalue0/WiRSa#11]
When assembling a WiRSa, there's almost no margin of tolerance for the height between the sandwiched WiRSa and the 3D printed case. The piece of foam tape for the display spacing in my particular parts kit was a little thick, and I didn't squish it down when soldering the display to the board. I only pressed it so it would adhere and then laid it down to solder. The assembled device wound up about a millimeter and change too tall and sliding the top cover in was really tight for my liking.

It might make sense to adjust the top lid to add some margin and/or include a recess in the bottom to give the Weimos module a place to go so it's not pressed against the bottom of the case. Or make the case a little taller and use foam tape as spacers and a way to keep the case tight.

I'm not a case or 3D designer, so I can't contribute a fix, but hopefully this feedback can help for future builders.

**Comment by nullvalue0** [comment]
You're right, this has been an issue. I've been using a piece of paper or pencil eraser to gently push the screen down as I push the cover of the top - but I've now corrected the issue by making the enclosure slightly taller. If you'd like a replacement, let me know and I can send you one for cost of shipping.
