### ISSUE TITLE
can't do incoming connections, wifi drops

### ISSUE THREAD

**Issue by tynbendad** [nullvalue0/WiRSa#3]
from wirsa.ino (line 1025 currently):
>void readBackSwitch()
>{ //not sure why but when in a call, SW1 analog read hangs the connection
>  //only concerned about 'back' button push anyways, hence this function

this issue looks like it explains the reason why and a workaround (the wifi module also uses part of the analog to digital converter): https://github.com/esp8266/Arduino/issues/1634

your current workaround to avoid the analogRead when not in command mode, works for outgoing usage, but is insufficient for incoming connections since the wifi drops while waiting for a connection in command mode.

**Comment by tynbendad** [comment]
i've tested adding a "delay(3);" after both analogRead() calls (both around current lines 1015-1018) and it no longer disconnects wifi.
(also needed to change waitKey() to be declared as void since latest IDE complained about no return statement.)

**Comment by tynbendad** [comment]
also, with the latest arduino IDE (2.2.1) and libraries, this other workaround from Alwyz's original code fails (incoming connections close immediately), and is no longer needed (from around line 1094 in current .ino):
>    WiFiClient tempClient = tcpServer.available(); // this is the key to keeping the connection open
>    tcpClient = tempClient; // hand over the new connection to the global client
>    tempClient.stop();   // stop the temporary one

replacing with this lets incoming connections persist:
>    WiFiClient tcpClient = tcpServer.available();

**Comment by nullvalue0** [comment]
This is awesome, thanks for the help on all this. Need to update my IDE.  If you don't mind doing a pull request, I'll merge in your modifications.

**Comment by tynbendad** [comment]
Sure thing. I'm going to add the speed dial to atdt command and another change to help me debug connecting my retro systems together, then I'll put it all in a pull request.

**Comment by tynbendad** [comment]
unrelated to the issue topic but fwiw, i also have a problem with the "ch340" driver on windows, the latest one that windows keeps automatically installing doesn't work with the firmware updater... i had to install one i got from sparkfun's website and then every day i've had to uninstall the new one (which puts the old one back).

**Comment by tynbendad** [comment]
incoming request issue is closed with https://github.com/nullvalue0/WiRSa/pull/4 - thanks
