### ISSUE TITLE
Use the microUSB port as a USB serial port (Communications Device Class).

### ISSUE THREAD

**Issue by mkatzNU** [nullvalue0/WiRSa#5]
Implement a CDC USB device on the micro USB side.

This will allow the WiRSa to be in between the two devices.

You now have the following options:
1. micro USB to DB-9 connection
2. micro USB to WiFi connection
3. DB-9 to WiFi connection.

I can place the WiRSa in between my tera term session (via the micro USB port) and my target computer connected to the DB-9.  I can then switch to local mode and have the WiRSa transmit files on the SD card to the DB-9 m(see my next suggestion).

This would allow the WiRSa to function as a very powerful USB to Serial Adapter.

**Comment by mkatzNU** [comment]
CDC stands for Communications Device Class.  That is what the USB spec calls a virtual uart.

The programming of the ESP is done via a virtual comm port when the cpu is in boot mode so I know it can support it.  That is how NodeMCU-PyFlasher.exe programs the ESP flash.  If the bootloader can do it, the CPU can do it when not in bootloader mode.

**Comment by mkatzNU** [comment]
I don't think this idea will work without additional hardware.  It looks like the second UART is output only because it shares a pin with the flash chip interface.

It might be worth if for some additional expense to use some kind of I2C to use Serial chip (I think FTDI makes one) to implement this.

**Comment by nullvalue0** [comment]
Ok thanks for digging in. I'll close this issue for now but will keep it in mind for a future hardware revision.
